from Products.Zuul.interfaces import IInfo, IComponentInfo
from Products.Zuul.form import schema
from Products.Zuul.utils import ZuulMessageFactory as _t

class ISLADataSourceInfo(IInfo):
    newId = schema.Text(title=_t(u'Name'),
                       xtype="idfield",
                       description=_t(u'The name of this datasource'))
    type = schema.Text(title=_t(u'Type'),
                       readonly=True)
    oid = schema.Text(title=_t(u'OID'))
    enabled = schema.Bool(title=_t(u'Enabled'))

class ISLASInfo(IComponentInfo):
    """
    Info adapter for SLAS components.
    """
    instance = schema.Text(title=u"Instance", readonly=True, group='Overview')
    rttMonCtrlAdminOwner = schema.Text(title=u"Owner", readonly=True, group='Details')
    rttMonCtrlAdminTag = schema.Text(title=u"Tag", readonly=True, group='Details')
    rttMonCtrlAdminRttType = schema.Text(title=u"Type", readonly=True, group='Overview')
    rttMonCtrlAdminThreshold = schema.Text(title=u"Threshold", readonly=True, group='Details')
    rttMonCtrlAdminFrequency = schema.Text(title=u"Frequency", readonly=True, group='Overview')
    rttMonCtrlAdminTimeout = schema.Text(title=u"Timeout", readonly=True, group='Details')
    rttMonCtrlAdminVerifyData = schema.Text(title=u"Verify", readonly=True, group='Details')
    rttMonCtrlAdminStatus = schema.Text(title=u"Status", readonly=True, group='Overview')
    rttMonCtrlAdminNvgen = schema.Text(title=u"NVGen", readonly=True, group='Details')
    rttMonCtrlAdminGroupName = schema.Text(title=u"Group", readonly=True, group='Overview')
    rttMonEchoAdminProtocol = schema.Text(title=u"Type", readonly=True, group='Details')
    rttMonEchoAdminTargetAddress = schema.Text(title=u"Echo Target", readonly=True, group='Details')
    rttMonEchoAdminPktDataRequestSize = schema.Text(title=u"Request packet size", readonly=True, group='Details')
    rttMonEchoAdminPktDataResponseSize = schema.Text(title=u"Repsonse packet size", readonly=True, group='Details')
    rttMonEchoAdminTargetPort = schema.Text(title=u"Target port", readonly=True, group='Details')
    rttMonEchoAdminSourceAddress = schema.Text(title=u"Source", readonly=True, group='Details')
    rttMonEchoAdminSourcePort = schema.Text(title=u"Source port", readonly=True, group='Details')
    rttMonEchoAdminControlEnable = schema.Text(title=u"Enabled", readonly=True, group='Details')
    rttMonEchoAdminTOS = schema.Text(title=u"TOS", readonly=True, group='Details')
    rttMonEchoAdminLSREnable = schema.Text(title=u"LSR", readonly=True, group='Details')
    rttMonEchoAdminTargetAddressString = schema.Text(title=u"Target String", readonly=True, group='Details')
    rttMonEchoAdminNameServer = schema.Text(title=u"Name server", readonly=True, group='Details')
    rttMonEchoAdminOperation = schema.Text(title=u"Operation", readonly=True, group='Details')
    rttMonEchoAdminHTTPVersion = schema.Text(title=u"HTTP Version", readonly=True, group='Details')
    rttMonEchoAdminURL = schema.Text(title=u"URL", readonly=True, group='Details')
    rttMonEchoAdminCache = schema.Text(title=u"Cached", readonly=True, group='Details')
    rttMonEchoAdminInterval = schema.Text(title=u"Interval", readonly=True, group='Details')
    rttMonEchoAdminNumPackets = schema.Text(title=u"Packet count", readonly=True, group='Details')
    rttMonEchoAdminProxy = schema.Text(title=u"Proxy", readonly=True, group='Details')
    rttMonEchoAdminString1 = schema.Text(title=u"String 1", readonly=True, group='Details')
    rttMonEchoAdminString2 = schema.Text(title=u"String 2", readonly=True, group='Details')
    rttMonEchoAdminString3 = schema.Text(title=u"String 3", readonly=True, group='Details')
    rttMonEchoAdminString4 = schema.Text(title=u"String 4", readonly=True, group='Details')
    rttMonEchoAdminString5 = schema.Text(title=u"String 5", readonly=True, group='Details')
    rttMonEchoAdminMode = schema.Text(title=u"Mode", readonly=True, group='Details')
    rttMonEchoAdminVrfName = schema.Text(title=u"VRF Name", readonly=True, group='Details')
    rttMonEchoAdminCodecType = schema.Text(title=u"Codec", readonly=True, group='Details')
    rttMonEchoAdminCodecInterval = schema.Text(title=u"Codec interval", readonly=True, group='Details')
    rttMonEchoAdminCodecPayload = schema.Text(title=u"Codec payload", readonly=True, group='Details')
    rttMonEchoAdminCodecNumPackets = schema.Text(title=u"Codec packet count", readonly=True, group='Details')
    rttMonEchoAdminICPIFAdvFactor = schema.Text(title=u"ICPIF Adv factor", readonly=True, group='Details')
    rttMonEchoAdminLSPFECType = schema.Text(title=u"LSP FEC type", readonly=True, group='Details')
    rttMonEchoAdminLSPSelector = schema.Text(title=u"LSP selector", readonly=True, group='Details')
    rttMonEchoAdminLSPReplyMode = schema.Text(title=u"LSP reply mode", readonly=True, group='Details')
    rttMonEchoAdminLSPTTL = schema.Text(title=u"LSP TTL", readonly=True, group='Details')
    rttMonEchoAdminLSPExp = schema.Text(title=u"LSP Exp", readonly=True, group='Details')
    rttMonEchoAdminPrecision = schema.Text(title=u"Precision", readonly=True, group='Details')
    rttMonEchoAdminProbePakPriority = schema.Text(title=u"Probe priority", readonly=True, group='Details')
    rttMonEchoAdminOWNTPSyncTolAbs = schema.Text(title=u"OWNTP sync tol Abs", readonly=True, group='Details')
    rttMonEchoAdminOWNTPSyncTolPct = schema.Text(title=u"OWNTP sync tol Pct", readonly=True, group='Details')
    rttMonEchoAdminOWNTPSyncTolType = schema.Text(title=u"OWNTP sync tol type", readonly=True, group='Details')
    rttMonEchoAdminCalledNumber = schema.Text(title=u"Called number", readonly=True, group='Details')
    rttMonEchoAdminDetectPoint = schema.Text(title=u"Detection point", readonly=True, group='Details')
    rttMonEchoAdminGKRegistration = schema.Text(title=u"GK registration", readonly=True, group='Details')
    rttMonEchoAdminSourceVoicePort = schema.Text(title=u"Source voice port", readonly=True, group='Details')
    rttMonEchoAdminCallDuration = schema.Text(title=u"Call duration", readonly=True, group='Details')
    rttMonEchoAdminLSPReplyDscp = schema.Text(title=u"LSP reply Description", readonly=True, group='Details')
    rttMonEchoAdminLSPNullShim = schema.Text(title=u"LSP Shim", readonly=True, group='Details')
    rttMonEchoAdminTargetMPID = schema.Text(title=u"Target MPID", readonly=True, group='Details')
    rttMonEchoAdminTargetDomainName = schema.Text(title=u"Target domain", readonly=True, group='Details')
    rttMonEchoAdminTargetVLAN = schema.Text(title=u"Target VLAN", readonly=True, group='Details')
    rttMonEchoAdminEthernetCOS = schema.Text(title=u"Ethernet COS", readonly=True, group='Details')
    rttMonEchoAdminLSPVccvID = schema.Text(title=u"LSP Vccv ID", readonly=True, group='Details')
    rttMonEchoAdminTargetEVC = schema.Text(title=u"Target EVC", readonly=True, group='Details')